import { NextPage } from 'next';
import Head from 'next/head';
import React, { useMemo } from 'react';
import classNames from 'classnames';
import { Property } from 'csstype';
import styles from './DefaultLayout.module.scss';
import useDarkMode from '../../traits/DarkMode';

type LayoutProps = {
  alignItems?: Property.AlignItems,
  justifyContent?: Property.JustifyContent
  footerExtraClasses?: string;
}

const DefaultLayout: NextPage<LayoutProps> = function DefaultLayout({
  alignItems,
  justifyContent,
  footerExtraClasses,
  children,
}) {
  return (
    <div className="page-container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={classNames(styles.main)}
        style={{ alignItems, justifyContent }}
      >
        {children}
      </main>

      <footer className={classNames(styles.footer, footerExtraClasses)}>
        <em>A document with a privacy policy? </em>
      </footer>
    </div>
  );
};

DefaultLayout.defaultProps = {
  justifyContent: 'flex-start',
  alignItems: 'stretch',
  footerExtraClasses: '',
};

export default DefaultLayout;
